name: pdf_optimizer
description: "Optimizer for Text PDF"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  path: ^1.8.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pdf_optimizer/main.py
    - assets/pdf_optimizer/optimize.py   
    - assets/pdf_optimizer/pdf.py  
    - assets/pdf_optimizer/RealESRGAN_x4/RealESRGAN_x4.pth